### ISSUE TITLE
Upphovsman för märken

### ISSUE THREAD

**Issue by elmaxe** [datasektionen/damm#28]
Lägg till upphovsman för märken trots allt. Visa information om att upphovsmannen måste acceptera för att kunna läggas in.

- GDPR-grej, hämta alla märken som är skapade av x

**Comment by bullfest** [comment]
Inte gdpr, copyright ;)

Som gammal prylis så kan jag säga att den eviga devisen bör vara "får endast kopieras i smyg".

Sen, in a serious note så alla märken jag gjort är under CC0 (även om jag uppskattar en attribution :wink:)

**Comment by elmaxe** [comment]
@bullfest grejen med GDPR är att vi egentligen inte får lagra personuppgifter utan tillstånd från personen, därför måste vi fråga personen om tillstånd, det var det jag syftade på med GDPR :)
