### ISSUE TITLE
Märkesarkiv

### ISSUE THREAD

**Issue by elmaxe** [datasektionen/damm#6]
Digitalisera "märkesarkivet" genom att integrera ett märkesarkiv i damm.

Låt admins/prylis få rättigheter att lägga upp märken producerade av sektionen. Kan vi få ut vem som är nuvarande prylis ur pls/dfunkt? (Troligen)

Märke
- Namn
- Utgivningsår
- Bild
- Beskrivning
- Source-filer (pdf/.ai/svg)
- Antal producerade
- Pris
- ordernummet, underlättar framtida ordrar
- Skapad av

**Comment by bullfest** [comment]
> Låt admins/prylis få rättigheter att lägga upp märken producerade av sektionen. Kan vi få ut vem som är nuvarande prylis ur pls/dfunkt? (Troligen)

Ja det går (ur dfunkt) :)

Bra att veta är att det finns foton av alla märken innan 2015 i varje fall när jag och dåvarande historiker tog grymma bilder på alla märken.

**Comment by elmaxe** [comment]
Härligt!

**Comment by elmaxe** [comment]
https://i.imgur.com/iybW1Dh.png
